version: "3"

services:
  scheduled-events-api:
    image: scheduled-events-api:latest
    container_name: scheduled-events-api
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
